# See PEP 518: https://www.python.org/dev/peps/pep-0518/ for info on this file's structure.

[tool.pyflow]
name = ""
py_version = "3.7"
version = "0.1.0"


[tool.pyflow.scripts]


[tool.pyflow.dependencies]
methodtools = "^0.4.5"
loguru = "^0.5.3"
geopy = "^2.2.0"


[tool.pyflow.dev-dependencies]
black = "^21.7b0"
pytest = "^6.2.4"

